config/routes.rb
Rails.application.routes.draw do

  get 'invoice/index'

  resources :statuses

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  get 'home/index'


   root 'home#index'








end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_one :appointment


  validates :fee, numericality:  {:greater_than_or_equal_to => 0,
                                  :message => " Only positive numbers are allowed" }


end

app/controllers/diagnostics_controller.rb
class DiagnosticsController < ApplicationController
  before_action :set_diagnostic, only: [:show, :edit, :update, :destroy]

  # GET /diagnostics
  # GET /diagnostics.json
  def index
    @diagnostics = Diagnostic.all
   # @diagnostics = Diagnostic.appointment().page(params[:page]).per(50)
  end

  # GET /diagnostics/1
  # GET /diagnostics/1.json
  def show
  end

  # GET /diagnostics/new
  def new
    @diagnostic = Diagnostic.new
  end

  # GET /diagnostics/1/edit
  def edit
  end

  # POST /diagnostics
  # POST /diagnostics.json
  def create
    @diagnostic = Diagnostic.new(diagnostic_params)

    respond_to do |format|
      if @diagnostic.save
        format.html { redirect_to @diagnostic, notice: 'Diagnostic was successfully created.' }
        format.json { render :show, status: :created, location: @diagnostic }
      else
        format.html { render :new }
        format.json { render json: @diagnostic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostics/1
  # PATCH/PUT /diagnostics/1.json
  def update
    respond_to do |format|
      if @diagnostic.update(diagnostic_params)
        format.html { redirect_to @diagnostic, notice: 'Diagnostic was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnostic }
      else
        format.html { render :edit }
        format.json { render json: @diagnostic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostics/1
  # DELETE /diagnostics/1.json
  def destroy
    @diagnostic.destroy
    respond_to do |format|
      format.html { redirect_to diagnostics_url, notice: 'Diagnostic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic
      @diagnostic = Diagnostic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostic_params
      params.require(:diagnostic).permit(:code, :description, :fee)
    end
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/views/diagnostics/_form.html.erb
<%= form_for(@diagnostic) do |f| %>
  <% if @diagnostic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnostic.errors.count, "error") %> prohibited this diagnostic from being saved:</h2>

      <ul>
      <% @diagnostic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_field :fee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnostics/edit.html.erb
<h1>Editing diagnostic</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnostic %> |
<%= link_to 'Back', diagnostics_path %>

app/views/diagnostics/index.html.erb
<h1>Listing All Diagnostics</h1>

<table>

  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Fee</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @diagnostics.each do |diagnostic| %>
      <tr>
        <td><%= diagnostic.code %></td>
        <td><%= diagnostic.description %></td>
        <td><%= diagnostic.fee %></td>
        <td><%= link_to 'Show', diagnostic %></td>
        <td><%= link_to 'Edit', edit_diagnostic_path(diagnostic) %></td>
        <td><%= link_to 'Delete', diagnostic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagnostic', new_diagnostic_path %>

app/views/diagnostics/new.html.erb
<h1>New diagnostic</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnostics_path %>

app/views/diagnostics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @diagnostic.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @diagnostic.description %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @diagnostic.fee %>
</p>

<%= link_to 'Edit', edit_diagnostic_path(@diagnostic) %> |
<%= link_to 'Back', diagnostics_path %>