config/routes.rb
Rails.application.routes.draw do

  get 'invoice/index'

  resources :statuses

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  get 'home/index'


   root 'home#index'








end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, :through => :appointments
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:physicianname, :physicianaddress, :physicianphone)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :physicianname %><br>
    <%= f.text_field :physicianname %>
  </div>
  <div class="field">
    <%= f.label :physicianaddress %><br>
    <%= f.text_field :physicianaddress %>
  </div>
  <div class="field">
    <%= f.label :physicianphone %><br>
    <%= f.text_field :physicianphone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<h1>Listing All Physicians</h1>

<table>
  <thead>
    <tr>
      <th>Physician Name</th>
      <th>Physician Address</th>
      <th>Physician Phone</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.physicianname %></td>
        <td><%= physician.physicianaddress %></td>
        <td><%= physician.physicianphone %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Delete', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New Physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician Name:</strong>
  <%= @physician.physicianname %>
</p>

<p>
  <strong>Physician Address:</strong>
  <%= @physician.physicianaddress %>
</p>

<p>
  <strong>Physician Phone:</strong>
  <%= @physician.physicianphone %>
</p>

<p>
  <strong> Patient:</strong>
  <% @physician.patients.each do |x| %>
         <%= x.patientname %>
  <% end %>
</p>

<p>
  <strong> Pending Appointments:</strong>
  <% @physician.appointments.each do |date| %>

      <% if date.date >= Time.now %>
             <%=  date.date.strftime("%m/%d/%Y") %>
      <% elsif date.date < Time.now %>
             <%= 'No Current Appointments' %>
      <% end %>
  <% end %>
</p>


<p>
  <strong>  Appointment Date:</strong>
  <% Time.now  %>
  <% @physician.appointments.each do |date| %>
        <%= date.date.strftime("%m/%d/%Y") %>
  <% end %>
</p>

<p>
  <strong> Days until Appointment:</strong>
  <% Time.now  %>
  <% @physician.appointments.each do |d| %>
      <% d =  d.date.to_date - Time.now.to_date  %>
      <% if d >= 0 %>
            <%= d.to_i  %> Days
      <% elsif d < 0 %>
               <%= '0 Days' %>
      <% end %>
  <% end %>
</p>


<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>