config/routes.rb
Rails.application.routes.draw do

  get 'invoice/index'

  resources :statuses

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  get 'home/index'


   root 'home#index'








end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndividualProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="jquery.datetimepicker.css" >
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">

  <link rel="stylesheet" type="text/css" href="./js/jquery.datetimepicker.css" />
  <script src="./js/jquery.datetimepicker.js"></script>




</head>


<body >
<!--style = "background-image: url('/assets/relax.jpeg'); background-size: cover; " -->

  <ul class="nav nav-tabs">

    <li class="active"><%= link_to 'Home', root_path %></li>


    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Patients
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li class="active"><%= link_to 'New Patient', new_patient_path%></li>

      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Appointments
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li class="active"><%= link_to 'List of All Appointments',appointments_path %></li>



      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Physicians
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li class="active"><%= link_to 'List of All Physicians', physicians_path%></li>
      </ul>
    </li>


    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        System Admin
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li class="active"><%= link_to 'List of Patients', patients_path%></li>

        <li class="active"><%= link_to 'Add Physician', new_physician_path %> </li>
        <li class="active"><%= link_to 'Edit Physician', physicians_path %> </li>
        <li class="active"><%= link_to 'Delete Physician', physicians_path %> </li>
        <li class="active"><%= link_to 'Add Diagnostic Codes', new_diagnostic_path %></li>
        <li class="active"><%= link_to 'Edit Diagnostic Codes', diagnostics_path %></li>
        <li class="active"><%= link_to 'Delete Diagnostic Codes', diagnostics_path %></li>
      </ul>
    </li>

  </ul>







  <%= yield %>



</body>
</html>